config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :paper_trail_versions, controller: 'versions'
  resources :companies, :futsal_fields, :game_registrations, :teams, :highlights, 
            :highlight_types, :goal_marks, :user_futsal_game_with_users,
            :futsal_tournament_player_registrations, :futsal_tournament_team_registrations, 
            :futsal_tournaments, :futsal_positions, :futsal_game_player_positions,
            :futsal_game_player_position_changes, :futsal_game_invitations, :user_futsal_trophies,
            :futsal_trophies, :nationalities

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :show_statistics_full
    end
  end
  resources :authentications, only: [:destroy]

  resources :futsal_games do
    member do
      get :affect_or_invite_players
      get :parse_match_resume
      get :parse_stats
      get :affect_player_to_team
      get :calculate_goalkeeper_position
      get :send_email_to_prevent_statistics_are_up_to_date
      get :send_email_to_prevent_teams_are_up_to_date
      get :teams_making
    end
  end

  resources :goals do
    member do
      get :mark_goal
      get :show_embed
    end
  end

  get '/export_db', to: 'admin#export_db'
  get '/show_db', to: 'admin#show_db_view'
  get '/create_seeds', to: 'admin#create_seeds'
  get '/show_admin', to: 'admin#show'
  get '/show_fixtures_users', to: 'admin#show_fixtures_users_view'
  get '/show_fixtures_futsal_games', to: 'admin#show_fixtures_futsal_games_view'
  get '/show_fixtures_teams', to: 'admin#show_fixtures_teams_view'

  get '/how_the_mark_is_calculated', to: 'pages#how_the_mark_is_calculated'
end

app/controllers/futsal_games_controller.rb
class FutsalGamesController < ApplicationController
  authorize_resource
  before_action :set_futsal_game, only: [:show, :edit, :update, :destroy, :parse_match_resume, :calculate_goalkeeper_position, 
    :send_email_to_prevent_statistics_are_up_to_date, :send_email_to_prevent_teams_are_up_to_date, :affect_or_invite_players, 
    :teams_making, :parse_stats]
  # GET /futsal_games
  def index
    @q = FutsalGame.ransack(params[:q])
    @futsal_games = @q.result.joins(:team_home, :team_outside).page(params[:page])
  end
  # GET /futsal_games/1
  def show
    @minutes_buts = []
    @ecart = []
    goal_1 = 0
    @score_1 = []
    @score_2 = []
    goal_2 = 0
    @futsal_game.goals.order_by_time.each do |goal|
      goal.team == @futsal_game.team_home ? goal_1 = goal_1 + 1 : goal_2 = goal_2 + 1      
      @minutes_buts.push(goal.time)
      @ecart.push((goal_1-goal_2).to_s)
      @score_1.push(goal_1)
      @score_2.push(goal_2)
    end
  end

  # GET /futsal_games/new
  def new
    @futsal_game = FutsalGame.new
  end

  def affect_or_invite_players

    #@dispo = User.unscoped.where('id NOT IN (?)',
    #          GameRegistration.where('futsal_game_id IN (?) AND user_id IS NOT NULL',
    #            FutsalGame.where("date > ? AND date < ? ", @futsal_game.date.beginning_of_day(), @futsal_game.date.end_of_day()).pluck(:id)
    #          ).pluck(:user_id)
    #        ).where('id IN (?)',
    #          GameRegistration.where('futsal_game_id IN (?) AND user_id IS NOT NULL',
    #            FutsalGame.where("futsal_field_id = ? AND (team_home_id = ? OR team_outside_id = ? OR team_home_id = ? OR team_outside_id = ?)", @futsal_game.futsal_field_id, @futsal_game.team_home, @futsal_game.team_home, @futsal_game.team_outside, @futsal_game.team_outside).pluck(:id)
    #          ).pluck(:user_id)
    #        ).order("match DESC").order(:first_name, :last_name)
    @dispo = []
    @users = User.all
    @game_registrations_possibles_teams = [Team.new, @futsal_game.team_home, @futsal_game.team_outside]
    @stats_players_name = @futsal_game.get_stats_players_name
  end

  # GET /futsal_games/1/edit
  def edit
  end

  def send_email_to_prevent_statistics_are_up_to_date
    @futsal_game.game_registrations.each do |game_registration|
      UserMailer.match_update(game_registration).deliver
    end
    redirect_to @futsal_game
  end

  def send_email_to_prevent_teams_are_up_to_date
    @futsal_game.game_registrations.each do |game_registration|
      UserMailer.teams_is_online(game_registration).deliver
    end
    redirect_to @futsal_game
  end

  def parse_match_resume
  end

  def parse_stats

  end

  def teams_making
    @team_making = MatchMaking.new(game_registrations: @futsal_game.game_registrations)
  end

  def calculate_goalkeeper_position
    @futsal_game.andand.futsal_game_player_position_by_team_and_position(@futsal_game.team_home, 1).delete_all
    
    futsal_game_player_position = FutsalGamePlayerPosition.new
    @futsal_game.andand.goal_and_change_by_team_and_position(@futsal_game.team_outside, @futsal_game.team_home, 1).each_with_index do |goal, index|
      if(index == 0 || (goal.instance_of? FutsalGamePlayerPositionChange) || ((futsal_game_player_position.andand.game_registration.andand.user != goal.goalkeeper) && !goal.goalkeeper.nil?))
        if goal.instance_of? FutsalGamePlayerPositionChange
          if( index == 0 )
            futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.game_registration_player_out.user.id, @futsal_game).first
            futsal_game_player_position.futsal_position_id = 1
            futsal_game_player_position.begin_time = 0
          end
          futsal_game_player_position.end_time = goal.time
          futsal_game_player_position.save

          futsal_game_player_position = FutsalGamePlayerPosition.new
          futsal_game_player_position.futsal_position_id = 1
          futsal_game_player_position.begin_time = goal.time
          futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.game_registration_player_in.user.id, @futsal_game).first
        else
          if( index > 0 )
            end_time = ((futsal_game_player_position.end_time + goal.time) / 2)
            futsal_game_player_position.end_time = end_time
            futsal_game_player_position.save
          end
          futsal_game_player_position = FutsalGamePlayerPosition.new
          futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.goalkeeper, @futsal_game).first
          futsal_game_player_position.futsal_position_id = 1
          futsal_game_player_position.calculated = true
          if( index > 0 )
            futsal_game_player_position.begin_time = end_time
          else
            futsal_game_player_position.begin_time = 0
          end
        end
      end
      futsal_game_player_position.end_time = goal.time
    end
    if !futsal_game_player_position.game_registration.nil?
      futsal_game_player_position.end_time = @futsal_game.duration * 60
      futsal_game_player_position.save
    end

    @futsal_game.andand.futsal_game_player_position_by_team_and_position(@futsal_game.team_outside, 1).delete_all
    
    futsal_game_player_position = FutsalGamePlayerPosition.new
    @futsal_game.andand.goal_and_change_by_team_and_position(@futsal_game.team_home, @futsal_game.team_outside, 1).each_with_index do |goal, index|
      if(index == 0 || (goal.instance_of? FutsalGamePlayerPositionChange) || ((futsal_game_player_position.andand.game_registration.andand.user != goal.goalkeeper) && !goal.goalkeeper.nil?))
        if goal.instance_of? FutsalGamePlayerPositionChange
          if( index == 0 )
            futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.game_registration_player_out.user.id, @futsal_game).first
            futsal_game_player_position.futsal_position_id = 1
            futsal_game_player_position.begin_time = 0
          end
          futsal_game_player_position.end_time = goal.time
          futsal_game_player_position.save

          futsal_game_player_position = FutsalGamePlayerPosition.new
          futsal_game_player_position.futsal_position_id = 1
          futsal_game_player_position.begin_time = goal.time
          futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.game_registration_player_in.user.id, @futsal_game).first
        else
          if( index > 0 )
            end_time = ((futsal_game_player_position.end_time + goal.time) / 2)
            futsal_game_player_position.end_time = end_time
            futsal_game_player_position.save
          end
          futsal_game_player_position = FutsalGamePlayerPosition.new
          futsal_game_player_position.game_registration = GameRegistration.where('user_id = ? AND futsal_game_id = ?', goal.goalkeeper, @futsal_game).first
          futsal_game_player_position.futsal_position_id = 1
          futsal_game_player_position.calculated = true
          if( index > 0 )
            futsal_game_player_position.begin_time = end_time
          else
            futsal_game_player_position.begin_time = 0
          end
        end
      end
      futsal_game_player_position.end_time = goal.time
    end
    futsal_game_player_position.end_time = @futsal_game.duration * 60
    futsal_game_player_position.save
    redirect_to @futsal_game
  end 

  def affect_player_to_team
    @game_registration = GameRegistration.find(params[:game_registration])
    @team = Team.find(params[:team])
    @game_registration.team = @team
    @game_registration.save
    redirect_to @game_registration.futsal_game, notice: 'Inscriptions mise a jour'
  end

  # POST /futsal_games
  def create
    @futsal_game = FutsalGame.new(futsal_game_params)

    if @futsal_game.save
      redirect_to @futsal_game, notice: 'Futsal game was successfully created.'
    else
      render :new
    end
  end
  # PATCH/PUT /futsal_games/1
  def update
    if @futsal_game.update(futsal_game_params)
      redirect_to @futsal_game, notice: 'Futsal game was successfully updated.'
    else
      render :edit
    end
  end
  # DELETE /futsal_games/1
  def destroy
    @futsal_game.destroy
    redirect_to futsal_games_url, notice: 'Futsal game was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_futsal_game
      @futsal_game = FutsalGame.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def futsal_game_params

      params.require(:futsal_game).permit(:date, :duration, :futsal_field_id, :futsal_tournament_id, :team_home_id, :team_outside_id,
                                          :score_home, :score_outside, :video_link, :match_resume_link, :match_stats_link,
                                          :video_secondary_beginning, :match_resume_link_secondary,
                                          game_registrations_attributes: [:id, :user_id, :futsal_game_id, :team_id, :goal, :assist, :player_footbar_name, :_destroy],
                                          futsal_game_player_position_attributes: [:id, :game_registration_id, :futsal_position_id, :begin_time, :end_time, :duration, :_destroy],
                                          futsal_game_invitations_attributes: [:id, :futsal_game_id, :user_id, :send_date, :status, :game_registration_id, :_destroy]);
    end
end

app/views/futsal_games/_chart.html.erb
<canvas id="myChart" width="100%" height="30px"></canvas>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: 
        ['',
            <% @minutes_buts.each do |minute_buts| %>
                '<%= minute_buts/60 %>',
            <% end %>
        ],
      datasets: [{
        label: 'Ecart',
        data: 
          ['',
              <% @ecart.each do |ecart| %>
                <%= ecart %>,
              <% end %>
          ],
        backgroundColor: [
            'rgba(190, 99, 132, 0.2)'
        ],
        borderColor: [
            'rgba(78,99,132,1)'
        ],
        borderWidth: 1,
        hidden: true
      },{
        label: '<%= @fustal_game.andand.team_home %> - Equipe 1',
        data: 
          ['',
              <% @score_1.each do |score| %>
                <%= score %>,
              <% end %>
          ],
        backgroundColor: [
            'rgba(190, 99, 12, 0.2)'
        ],
        borderColor: [
            'rgba(78,200,132,1)'
        ],
        borderWidth: 1
      },{
        label: '<%= @fustal_game.andand.team_outside %> - Equipe 2',
        data: 
          ['',
              <% @score_2.each do |score| %>
                <%= score %>,
              <% end %>
          ],
        backgroundColor: [
            'rgba(190, 99, 132, 0.2)'
        ],
        borderColor: [
            'rgba(78,99,132,1)'
        ],
        borderWidth: 1
      }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/futsal_games/_chart_players_stats.html.erb
<canvas id="myChartPlayers" width="100%" height="30px"></canvas>
<script>
var ctx = document.getElementById("myChartPlayers").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels:
        [
            <% game_registrations.each do |game_registration| %>
              '<%= game_registration.user %>',
            <% end %>
        ],
      datasets: [{
        label: 'Distance (km)',
        data:
          [
            <% game_registrations.each do |game_registration| %>
              '<%= ((game_registration.distance_run || 0) / 1000).round(2) %>',
            <% end %>
          ],
        backgroundColor: [
            'rgba(190, 99, 132, 0.2)'
        ],
        borderColor: [
            'rgba(78,99,132,1)'
        ],
        borderWidth: 1
      },{
        label: 'Nombre de passes',
        data:
          [
            <% game_registrations.each do |game_registration| %>
              '<%= game_registration.pass_number || 0 %>',
            <% end %>
          ],
        backgroundColor: [
            'rgba(190, 99, 12, 0.2)'
        ],
        borderColor: [
            'rgba(78,200,132,1)'
        ],
        borderWidth: 1
      }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

<br>

app/views/futsal_games/_form.html.erb
<%= simple_form_for(@futsal_game) do |f| %>
  <%= f.error_notification %>
  <%= f.button :submit %>
  <div class="row">
    <div class="col form-group">
      <label for="date"><%= f.label :date %></label>
      <%= f.input :date, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="col form-group">
      <label for="duration"><%= f.label :duration %></label>
      <%= f.input :duration, label: false, input_html: { class: "form-control" } %>
    </div>
  </div>


  <div class="row">
    <div class="col form-group">
      <label for="futsal_field"><%= f.label :futsal_field %></label>
      <%= f.association :futsal_field, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="col form-group">
      <label for="futsal_tournament"><%= f.label :futsal_tournament %></label>
      <%= f.association :futsal_tournament, label: false, input_html: { class: "form-control" } %>
    </div>
  </div>

  <div class="row">
    <div class="col form-group">
      <label for="team_home_id"><%= f.label :team_home_id %></label>
      <%= f.association :team_home, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="col-2 form-group">
      <label for="score_home"><%= f.label :score_home %></label>
      <%= f.input :score_home, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="col-2 form-group">
      <label for="score_outside"><%= f.label :score_outside %></label>
      <%= f.input :score_outside, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="col form-group">
      <label for="team_outside_id"><%= f.label :team_outside_id %></label>
      <%= f.association :team_outside, label: false, input_html: { class: "form-control" } %>
    </div>
  </div>
  <div class="row">
      <div class="col form-group">
        <label for="video_link"><%= f.label :video_link %></label>
        <%= f.input :video_link, label: false, input_html: { class: "form-control" } %>
        <label for="video_secondary_beginning"><%= f.label :video_secondary_beginning %></label>
        <%= f.input :video_secondary_beginning, label: false, input_html: { class: "form-control" } %>
      </div>
      <div class="col form-group">
        <label for="match_resume_link"><%= f.label :match_resume_link %></label>
        <%= f.input :match_resume_link, label: false, input_html: { class: "form-control" } %>
        <%= f.input :match_resume_link_secondary, label: false, input_html: { class: "form-control" } %>
      </div>
      <div class="col form-group">
        <label for="match_stats_link"><%= f.label :match_stats_link %></label>
        <%= f.input :match_stats_link, label: false, input_html: { class: "form-control" } %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/futsal_games/_show_team_position.html.erb
<table class="table table-hover table-sm table-bordered">
  <tr>
    <thead class="thead-inverse">
      <th>Pos.</th>
      <th>Joueur</th>
      <th>Deb</th>
      <th>Fin</th>
      <th>Calculé ?</th>
      <% if can? :edit, FutsalGamePlayerPosition %>
        <th></th>
      <% end %>
    </thead>
  </tr>
  <% team_position.each do |futsal_game_player_position| %>
    <% if futsal_game_player_position.instance_of? FutsalGamePlayerPosition %>
      <tr>
        <td><%= futsal_game_player_position.futsal_position.andand.abbreviation %></td>
        <td><%= futsal_game_player_position.game_registration.user %></td>
        <td><%= formatted_match_time(futsal_game_player_position.begin_time) %></td>
        <td><%= formatted_match_time(futsal_game_player_position.end_time) %></td>
        <td><%= futsal_game_player_position.calculated %></td>
        <% if can? :edit, FutsalGamePlayerPosition %>
          <td><%= link_to icon('pencil').html_safe, edit_futsal_game_player_position_path(futsal_game_player_position), target: "_blank" %></td>
        <% end %>
      </tr>
    <% elsif futsal_game_player_position.instance_of? FutsalGamePlayerPositionChange %>
      <tr>
        <td><%= futsal_game_player_position.futsal_position.abbreviation %></td>
        <th>
          <%= icon('refresh') %> Changement
        </th>
        <td>
          <%= formatted_match_time(futsal_game_player_position.andand.time) %>
        </td>
        <td>
          <%= icon('sign-in') %> <%= futsal_game_player_position.andand.game_registration_player_in.andand.user.to_s %>
        </td>
        <td>
          <%= icon('sign-out') %> <%= futsal_game_player_position.andand.game_registration_player_out.andand.user.to_s %>
        </td>
        <% if can? :edit, FutsalGamePlayerPositionChange %>
          <td><%= link_to icon('pencil').html_safe, edit_futsal_game_player_position_change_path(futsal_game_player_position), target: "_blank" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/futsal_games/affect_or_invite_players.html.erb
<% if can? :affect_player_to_team, @futsal_game %>
  <h3>Inscriptions</h3>
  <%= simple_form_for(@futsal_game) do |f| %>

    <%= f.simple_fields_for :game_registrations do |game_registration| %>
      <%= render 'game_registrations/game_registrations_field', f: game_registration, stats_players_name: @stats_players_name %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association "Inscrire", f, :game_registrations, partial: 'game_registrations/game_registrations_field' %>
    </div>

  Disponibles :
  <% @dispo.each do |user| %>
    <%= show_player(user) %>
  <% end %>

  <%= f.button :button, class: "btn btn-primary" do %>
    Valider
  <% end %>
  <% end %>
<% end %>

<% if can? :invite_player, @futsal_game %>
  <h3>Invitations</h3>
  <%= simple_form_for(@futsal_game) do |f| %>
    <%= f.simple_fields_for :futsal_game_invitations do |futsal_game_invitation| %>
      <%= render 'futsal_game_invitations/futsal_game_invitation_field', f: futsal_game_invitation %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association "Inviter", f, :futsal_game_invitations, partial: 'futsal_game_invitations/futsal_game_invitation_field' %>
    </div>

  Disponibles :
  <% @dispo.each do |user| %>
    <%= show_player(user) %>
  <% end %>

  <%= f.button :button, class: "btn btn-primary" do %>
    Valider
  <% end %>
  <% end %>
<% end %>

app/views/futsal_games/edit.html.erb
<h1>Editing Futsal Game</h1>

<%= render 'form', futsal_game: @futsal_game %>

<%= link_to 'Show', @futsal_game %> |
<%= link_to 'Back', futsal_games_path %>

app/views/futsal_games/new.html.erb
<h1>Organiser un match de futsal</h1>

<%= render 'form', futsal_game: @futsal_game %>

<%= link_to 'Back', futsal_games_path %>

app/views/futsal_games/show_embed.html.erb
<div class="link-previous-next">
  <%= link_to icon('angle-double-left') + " Précédent", futsal_game_path(@futsal_game.id - 1) %> | <%= link_to ("Suivant " + icon('angle-double-right')).html_safe, futsal_game_path(@futsal_game.id + 1) %>
</div>
<!-- Modal -->
<div class="modal fade" id="goal_modal" tabindex="-1" role="dialog" aria-labelledby="goal_modal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">But</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe id="iframe_goal" src="https://www.google.com" width="100%" height="500px"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function change_goal(id) {
    document.getElementById('iframe_goal').src = "../goals/" + id;
  }
</script>

<% if can? :affect_player_to_team, @futsal_game %>
  <%= simple_form_for(@futsal_game) do |f| %>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Inscriptions</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id='game_registrations'>
              <%= f.simple_fields_for :game_registrations do |game_registration| %>
                <%= render 'game_registrations/game_registrations_field', f: game_registration %>
              <% end %> 
              <div class='links'>
                <%= link_to_add_association "Inscrire", f, :game_registrations, partial: 'game_registrations/game_registrations_field' %>
              </div>
            </div>

            Disponibles :
            <% @dispo.each do |user| %>
              <%= show_player(user) %>
            <% end %>


          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            <%= f.button :button, class: "btn btn-primary" do %>
              Valider
            <% end %>
          </div>
        </div>
      </div>
    </div>    
  <% end %>
<% end %>

<% if !notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>
<div class="match_header">
  <div class="row">
    <div class="col date">
      <%= @futsal_game.date.strftime("%d/%m/%Y %H:%M") %>
    </div>
    <div class="col duration">
      <%= Time.at(@futsal_game.duration * 60).utc.strftime("%H:%M:%S") %>
    </div>
    <div class="col futsal_field">
      <%= @futsal_game.futsal_field.andand.name %>
    </div>
  </div>
  <div class="row">
    <div class="col team_name">
      <%= @futsal_game.team_home.andand.name %>
    </div>
    <div class="col">
      <div class="row score">
        <div class="col score_but">
          <%= @futsal_game.score_home %>
        </div>
        <div class="col-1">
          -
        </div>
        <div class="col score_but">
          <%= @futsal_game.score_outside %>
        </div>
      </div>  
    </div>
    <div class="col team_name">
      <%= @futsal_game.team_outside.andand.name %>
    </div>
  </div>
</div>
  <div class="row match_link">
    <% if !@futsal_game.video_link.nil?  && @futsal_game.video_link != "" %>
      <div class="col">
        <%= link_to icon('television') + " Voir la video du match", @futsal_game.video_link, target: "_blank", class: "btn btn-sm btn-block btn-outline-primary" %>
      </div>
    <% end %>
    <% if can? :affect_player_to_team, @futsal_game %>
      <div class="col">
        <button type="button" class="btn btn-sm btn-block btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
            <%= (icon('user-plus') + ' Inscrire un joueur').html_safe %>
          </button>
      </div>
    <% end %>
    <% if !@futsal_game.match_resume_link.nil? && @futsal_game.match_resume_link != "" %>
      <div class="col">
        <%= link_to icon('futbol-o') + " Voir le match sur le site du soccer", @futsal_game.match_resume_link, target: "_blank", class: "btn btn-sm btn-block btn-outline-primary" %>
      </div>
    <% end %>
  </div>

<%= render 'timeline', futsal_game: @futsal_game %> 

<div class="row goal_tab">
  <div class="col-sm-12 col-md-6">
    <%= render 'show_team_fifa', team: @futsal_game.team_home_players, futsal_game: @futsal_game %>
    <%= render 'show_team_position', team_position: @futsal_game.andand.futsal_game_player_position_by_team(@futsal_game.team_home) %>
  </div>
  
  <div class="col-sm-12 col-md-6">
    <%= render 'show_team_fifa', team: @futsal_game.team_outside_players, futsal_game: @futsal_game %>   
    <%= render 'show_team_position', team_position: @futsal_game.andand.futsal_game_player_position_by_team(@futsal_game.team_outside) %>
  </div>
</div>
<% if @futsal_game.has_stat %>
  <%= render 'chart', minutes_buts: @minutes_buts, ecart: @ecart, futsal_game: @futsal_game %>
<% end %>
<div class="row">
  <div class="col-sm-1 col-md-3"> 
  </div> 
  <div class="col-sm-10 col-md-6">    
    <% @futsal_game.andand.team_less_players.order_by_users_stats.each do |player| %>
        <div class="player">
          <%= show_player(player.user) %> 
          <% if can? :affect_player_to_team, @futsal_game %>
            Affecter :
            <%= link_to 'Equipe 1', affect_player_to_team_futsal_game_path(game_registration: player, team: @futsal_game.team_home) %> - 
            <%= link_to 'Equipe 2', affect_player_to_team_futsal_game_path(game_registration: player, team: @futsal_game.team_outside) %>
          <% end %>
        </div>
    <% end %>

    

    <%= render 'show_highlights_and_goals', futsal_game: @futsal_game %>
  </div>
</div>



<% if (can? :parse_match_resume, FutsalGame) && !@futsal_game.match_resume_link.nil? && @futsal_game.match_resume_link != "" %>
  <%= link_to 'Parse match resume', parse_match_resume_futsal_game_path(@futsal_game) %> |
<% end %>
<% if can? :edit, FutsalGame %>
  <%= link_to 'Edit', edit_futsal_game_path(@futsal_game) %> |
<% end %>
<%= link_to 'Back', futsal_games_path %>