config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :paper_trail_versions, controller: 'versions'
  resources :companies, :futsal_fields, :game_registrations, :teams, :highlights, 
            :highlight_types, :goal_marks, :user_futsal_game_with_users,
            :futsal_tournament_player_registrations, :futsal_tournament_team_registrations, 
            :futsal_tournaments, :futsal_positions, :futsal_game_player_positions,
            :futsal_game_player_position_changes, :futsal_game_invitations, :user_futsal_trophies,
            :futsal_trophies, :nationalities

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :show_statistics_full
    end
  end
  resources :authentications, only: [:destroy]

  resources :futsal_games do
    member do
      get :affect_or_invite_players
      get :parse_match_resume
      get :parse_stats
      get :affect_player_to_team
      get :calculate_goalkeeper_position
      get :send_email_to_prevent_statistics_are_up_to_date
      get :send_email_to_prevent_teams_are_up_to_date
      get :teams_making
    end
  end

  resources :goals do
    member do
      get :mark_goal
      get :show_embed
    end
  end

  get '/export_db', to: 'admin#export_db'
  get '/show_db', to: 'admin#show_db_view'
  get '/create_seeds', to: 'admin#create_seeds'
  get '/show_admin', to: 'admin#show'
  get '/show_fixtures_users', to: 'admin#show_fixtures_users_view'
  get '/show_fixtures_futsal_games', to: 'admin#show_fixtures_futsal_games_view'
  get '/show_fixtures_teams', to: 'admin#show_fixtures_teams_view'

  get '/how_the_mark_is_calculated', to: 'pages#how_the_mark_is_calculated'
end

app/models/game_registration.rb
class GameRegistration < ApplicationRecord
  resourcify

  belongs_to :user, optional: true
  belongs_to :futsal_game
  belongs_to :team, optional: true
  has_many :futsal_game_player_positions
  has_many :user_futsal_trophies, as: :linked_entity

  scope :order_by_stats, -> { order('rating desc') }

  scope :order_by_users_stats, -> { includes(:user).order('users.rating desc') }

  scope :order_by_futsal_game, -> { includes(:futsal_game).order('futsal_games.date desc') }

  scope :order_by_futsal_game_asc, -> { includes(:futsal_game).order('futsal_games.date') }

  scope :futsal_games_with_stats, -> { where("futsal_games.video_link <> ''") }

  scope :with_player_stats, -> { where('pass_number > 0') }

  def update_stats
    self.goal = self.futsal_game.goal_by_user(self.user).length
    self.assist = self.futsal_game.assist_by_user(self.user).length
    #if self.futsal_game.futsal_tournament
    #  self.futsal_game.futsal_tournament.update_stats
    #end
        # t.integer :goalkeeper_duration
        # t.integer :player_duration
        # t.integer :substitute_duration
    self.goalkeeper_goal_against = self.futsal_game.goalkeeper_goal_against_by_user(self.user).length
    self.goalkeeper_duration = futsal_game_player_positions.where(futsal_position_id: 1).sum(:duration)
    self.substitute_duration = futsal_game_player_positions.where(futsal_position_id: 100).sum(:duration)
    self.player_duration = (self.futsal_game.duration * 60) - self.goalkeeper_duration - self.substitute_duration
    self.rating = self.calculate_rating
    self.match_result = self.futsal_game.match_result(self.team)
  end

  def calculate_rating
    player_multiplier = (player_duration > 0 ? (60*60) / player_duration : 1)
    goalkeeper_multiplier = (goalkeeper_duration > 0 ? (60*60) / goalkeeper_duration : 1)

    self.user ? self.user.calculate_rating(goal: self.goal * player_multiplier, own_goal: 0, assist: self.assist * player_multiplier, goalkeeper_goal_against: self.goalkeeper_goal_against * goalkeeper_multiplier) : 0
 end

  def own_goal
    0
  end

  def to_s
    self.user.to_s + ' ' + self.futsal_game.to_s
  end

  def trainer_opinion
    game_level = calculate_game_level(self.user.rating, self.rating);
    trainer_opinion = ''

    if self.rating <= 65
       trainer_opinion = "Pas terrible, terrible ce match. Qu'est ce qui t'es arrivé ? T'es arrivé en retard ? On t'a volé tes chaussures ?"
    elsif self.rating >= 95
       trainer_opinion = "Waouh quel match. Un mélange de Zidane, Ronaldo, Messi et Cyril Rool dans la même personne. Awesome !"
    elsif game_level == -2
       trainer_opinion = "Un peu en dessous de ton niveau habituel. Mais ça arrive, souviens toi de Guivarc'h en 1998."
    elsif game_level == -1
       trainer_opinion = "Match pas terrible. Tu étais un peu le Bouna Sarr de ton équipe."
    elsif game_level == 0
       trainer_opinion = "Match dans la moyenne. C'est positif, tu es constant. On peut aussi dire que tu ne t'es pas foulé !"
    elsif game_level == 1
       trainer_opinion = "Bon match ! Rien d'exceptionnel, ne t'emballe pas mais c'était plutôt plaisant de te voir à ce niveau."
    else
       trainer_opinion = "Très bon match ! Si des recruteurs chinois étaient présents, tu peux commencer à apprendre le mandarin."
    end
    return trainer_opinion
  end

  def calculate_game_level(rating = 1, game_rating = 1)
      level = (game_rating.nil? ? 1 : game_rating) / (rating.nil? ? 1 : rating)

      if level < 0.93
        result = -2
      elsif level < 0.98
        result = -1
      elsif level < 1.025
        result = 0
      elsif level < 1.08
        result = 1
      else
        result = 2
      end

      return result
    end
end

app/controllers/game_registrations_controller.rb
class GameRegistrationsController < ApplicationController
  authorize_resource
  before_action :set_game_registration, only: [:show, :edit, :update, :destroy]
  # GET /game_registrations
  def index
    @q = GameRegistration.ransack(params[:q])
    @game_registrations = @q.result.page(params[:page])
  end
  # GET /game_registrations/1
  def show
  end

  # GET /game_registrations/new
  def new
    @game_registration = GameRegistration.new
  end

  # GET /game_registrations/1/edit
  def edit
  end

  # POST /game_registrations
  def create
    @game_registration = GameRegistration.new(game_registration_params)

    if @game_registration.save
      redirect_to @game_registration, notice: 'Game registration was successfully created.'
    else
      render :new
    end
  end
  # PATCH/PUT /game_registrations/1
  def update
    if @game_registration.update(game_registration_params)
      redirect_to @game_registration, notice: 'Game registration was successfully updated.'
    else
      render :edit
    end
  end
  # DELETE /game_registrations/1
  def destroy
    @game_registration.destroy
    redirect_to game_registrations_url, notice: 'Game registration was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_registration
      @game_registration = GameRegistration.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_registration_params

      params.require(:game_registration).permit(:user_id, :futsal_game_id, :team_id, :goal, :assist)

    end
end

app/views/game_registrations/_form.html.erb
<%= simple_form_for(@game_registration) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <label for="user"><%= f.label :user %></label>
      <%= f.association :user, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label for="futsal_game"><%= f.label :futsal_game %></label>
      <%= f.association :futsal_game, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label for="team"><%= f.label :team %></label>
      <%= f.association :team, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label for="goal"><%= f.label :goal %></label>
      <%= f.input :goal, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label for="assist"><%= f.label :assist %></label>
      <%= f.input :assist, label: false, input_html: { class: "form-control" } %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_registrations/_game_registrations_field.html.erb
<div class="row">
  <div class="col">
    <%= f.association :user, label: false, input_html: { class: "form-control" }, collection: @users %>
    <%= f.input :futsal_game_id, as: :hidden, input_html: { value: f.object.futsal_game.id } %>
  </div>
  <div class="col">
    <%= f.input :team_id, label: false, input_html: { class: "form-control" }, collection: @game_registrations_possibles_teams, selected: f.object.team.andand.id %>
  </div>
  <div class="col">
    <%= f.input :player_footbar_name, label: false, input_html: { class: "form-control" }, collection: @stats_players_name %>
  </div>
  <div class="col-1">
    <%= link_to_remove_association icon('times').html_safe, f %>
  </div>
</div>

app/views/game_registrations/edit.html.erb
<h1>Editing Game Registration</h1>

<%= render 'form', game_registration: @game_registration %>

<%= link_to 'Show', @game_registration %> |
<%= link_to 'Back', game_registrations_path %>

app/views/game_registrations/index.html.erb
<h1><%= t('.title') %><span class="badge"><%= @game_registrations.count %></span></h1>

<div class="row">
  <div class="col-2">
    <legend class="filter-title"><%= t :search_title %></legend>
    <fieldset class="filter-panel">
      <%= search_form_for @q do |f| %>

        <%= f.search_field :user_first_name_cont, {placeholder: t('activerecord.attributes.game_registration.user')} %>

        <%= f.search_field :futsal_game_date_cont, {placeholder: t('activerecord.attributes.game_registration.futsal_game')} %>

        <%= f.search_field :team_name_cont, {placeholder: t('activerecord.attributes.game_registration.team')} %>

        <%= f.search_field :goal_cont, {placeholder: t('activerecord.attributes.game_registration.goal')} %>

        <%= f.search_field :assist_cont, {placeholder: t('activerecord.attributes.game_registration.assist')} %>

        <br>
        <br>
        <%= f.submit class: 'btn btn-search-filter btn-sm btn-outline-primary' %>
      <% end %>
    </fieldset>
  </div>
  <div class="col">
    <div class="col-md-3 btn-new-top">
      <% if can? :create, GameRegistration %>
        <%= link_to (icon('plus') + " " + t('.new_button')).html_safe, url_for(action: :new), class: "btn btn-sm btn-outline-primary" %>
      <% end %>
    </div>
    <table class="table table-hover table-sm table-bordered">
      <thead>
        <tr>
    
          <th><%= sort_link(@q, :user_first_name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :futsal_game_date, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :team_name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :goal, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :assist, default_order: :asc) %></th>
    
          <th class="col-xs-1"></th>
        </tr>
      </thead>

      <tbody>
        <% @game_registrations.each do |game_registration| %>
          <tr>
    
            <td><%= game_registration.user %></td>
    
            <td><%= game_registration.futsal_game %></td>
    
            <td><%= game_registration.team %></td>
    
            <td><%= game_registration.goal %></td>
    
            <td><%= game_registration.assist %></td>
    
            <td>
              <%= link_to icon('eye').html_safe, game_registration %>
              <% if can? :edit, GameRegistration %>
                <%= link_to icon('pencil').html_safe, edit_game_registration_path(game_registration) %>
              <% end %>
              <% if can? :destroy, GameRegistration %>
                <%= link_to icon('times').html_safe, game_registration, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @game_registrations %>
  </div>
</div>

app/views/game_registrations/new.html.erb
<h1>New Game Registration</h1>

<%= render 'form', game_registration: @game_registration %>

<%= link_to 'Back', game_registrations_path %>

app/views/game_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @game_registration.user %>
</p>

<p>
  <strong>Futsal game:</strong>
  <%= @game_registration.futsal_game %>
</p>

<p>
  <strong>Team:</strong>
  <%= @game_registration.team %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @game_registration.goal %>
</p>

<p>
  <strong>Assist:</strong>
  <%= @game_registration.assist %>
</p>

<%= link_to 'Edit', edit_game_registration_path(@game_registration) %> |
<%= link_to 'Back', game_registrations_path %>