config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :paper_trail_versions, controller: 'versions'
  resources :companies, :futsal_fields, :game_registrations, :teams, :highlights, 
            :highlight_types, :goal_marks, :user_futsal_game_with_users,
            :futsal_tournament_player_registrations, :futsal_tournament_team_registrations, 
            :futsal_tournaments, :futsal_positions, :futsal_game_player_positions,
            :futsal_game_player_position_changes, :futsal_game_invitations, :user_futsal_trophies,
            :futsal_trophies, :nationalities

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :show_statistics_full
    end
  end
  resources :authentications, only: [:destroy]

  resources :futsal_games do
    member do
      get :affect_or_invite_players
      get :parse_match_resume
      get :parse_stats
      get :affect_player_to_team
      get :calculate_goalkeeper_position
      get :send_email_to_prevent_statistics_are_up_to_date
      get :send_email_to_prevent_teams_are_up_to_date
      get :teams_making
    end
  end

  resources :goals do
    member do
      get :mark_goal
      get :show_embed
    end
  end

  get '/export_db', to: 'admin#export_db'
  get '/show_db', to: 'admin#show_db_view'
  get '/create_seeds', to: 'admin#create_seeds'
  get '/show_admin', to: 'admin#show'
  get '/show_fixtures_users', to: 'admin#show_fixtures_users_view'
  get '/show_fixtures_futsal_games', to: 'admin#show_fixtures_futsal_games_view'
  get '/show_fixtures_teams', to: 'admin#show_fixtures_teams_view'

  get '/how_the_mark_is_calculated', to: 'pages#how_the_mark_is_calculated'
end

app/models/company.rb
class Company < ApplicationRecord
  resourcify

  def to_s
  	name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  authorize_resource
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # GET /companies
  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result.page(params[:page])
  end
  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end
  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end
  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params

      params.require(:company).permit(:name, :email_mask)

    end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <div class="form-group">
      <label for="name"><%= f.label :name %></label>
      <%= f.input :name, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="email_mask"><%= f.label :email_mask %></label>
      <%= f.input :email_mask, label: false, input_html: { class: "form-control" } %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1><%= t('.title') %><span class="badge"><%= @companies.count %></span></h1>

<div class="row">
  <div class="col-md-4">
    <legend class="filter-title"><%= t :search_title %></legend>
    <fieldset class="filter-panel">
      <%= search_form_for @q do |f| %>

        <%= f.search_field :name_cont, {placeholder: t('activerecord.attributes.company.name')} %>

        <%= f.search_field :email_mask_cont, {placeholder: t('activerecord.attributes.company.email_mask')} %>

        <br>
        <br>
        <%= f.submit class: 'btn btn-default btn-search-filter' %>
      <% end %>
    </fieldset>
  </div>
  <div class="col-md-8">
    <div class="col-md-3 btn-new-top">
      <% if can? :create, Company %>
        <%= link_to ('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> '+t('.new_button')).html_safe, url_for(action: :new), class: "btn btn-default" %>
      <% end %>
    </div>
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
    
          <th><%= sort_link(@q, :name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :email_mask, default_order: :asc) %></th>
    
          <th class="col-xs-1"></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr>
    
            <td><%= company.name %></td>
    
            <td><%= company.email_mask %></td>
    
            <td>
              <%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, company %>
              <% if can? :edit, Company %>
                <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_company_path(company) %>
              <% end %>
              <% if can? :destroy, Company %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, company, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @companies %>
  </div>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Email mask:</strong>
  <%= @company.email_mask %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>